# Generated by Django 5.1 on 2024-08-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_news_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
